{"name": "test_sum_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_August_001.Test_Credence object at 0x0000022C77C89950>\n\n    def test_sum_001(self):\n        a = 5\n        b = 2\n        sum = a + b\n        print(\"Sum of a and b is: \" + str(sum))\n        if sum == 5:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_August_001.py:17: AssertionError"}, "start": 1690967000772, "stop": 1690967000772, "uuid": "23d12d1a-6e43-4142-b772-755bef7cac0b", "historyId": "44e8538987793961e16b15670accc28b", "testCaseId": "44e8538987793961e16b15670accc28b", "fullName": "test_August_001.Test_Credence#test_sum_001", "labels": [{"name": "suite", "value": "test_August_001"}, {"name": "subSuite", "value": "Test_Credence"}, {"name": "host", "value": "LAPTOP-1DT8TVKR"}, {"name": "thread", "value": "10552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_August_001"}]}