{"name": "test_sum_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_August_001.Test_Credence object at 0x000001E4FA998250>\n\n    def test_sum_001(self):\n        a = 5\n        b = 2\n        sum = a + b\n        print(\"Sum of a and b is: \" + str(sum))\n        if sum == 5:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_August_001.py:17: AssertionError"}, "start": 1690966706565, "stop": 1690966706566, "uuid": "183976aa-af9c-4ceb-b8d4-511c1239b9f2", "historyId": "44e8538987793961e16b15670accc28b", "testCaseId": "44e8538987793961e16b15670accc28b", "fullName": "test_August_001.Test_Credence#test_sum_001", "labels": [{"name": "suite", "value": "test_August_001"}, {"name": "subSuite", "value": "Test_Credence"}, {"name": "host", "value": "LAPTOP-1DT8TVKR"}, {"name": "thread", "value": "7840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_August_001"}]}